[package]
name = "memory-stats"
authors = ["Arc-blroth <45273859+Arc-blroth@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
version = "1.1.0"
edition = "2021"
description = "A cross-platform memory profiler for Rust."
repository = "https://github.com/Arc-blroth/memory-stats"
readme = "README.md"
categories = ["development-tools::profiling"]
keywords = ["memory", "performance", "profiling"]

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["minwindef", "processthreadsapi", "psapi"] }

[target.'cfg(any(target_os = "linux", target_os = "android", target_os = "macos", target_os = "ios", target_os = "freebsd"))'.dependencies]
libc = "0.2"

[features]
# Always use the faster but less accurate /proc/self/statm statistics on Linux.
always_use_statm = []
