[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"
ignore = []

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
deny = []
skip = []

[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0"]
deny = []
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.95

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
